# Generated by Django 5.1.6 on 2025-02-11 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='nachname',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='vorname',
            new_name='lastname',
        ),
    ]
