# Generated by Django 5.1.6 on 2025-02-11 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_nachname_student_firstname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='alter',
            new_name='age',
        ),
    ]
