# Generated by Django 5.1.6 on 2025-02-10 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("vorname", models.CharField(max_length=100)),
                ("nachname", models.CharField(max_length=100)),
                ("alter", models.IntegerField()),
            ],
        ),
    ]
